### PR TITLE
Link status polling

### PR DESCRIPTION
**Pull request by hasnainvirk**
@SeppoTakalo @TuomoHautamaki  @artokin 
Somehow I cannot add Mike Tervonen here. Weird.

### CODE REVIEW

**Comment by SeppoTakalo** [comment]
CC: @mikter

**Comment by SeppoTakalo** [comment]
What does this `k64f_eth_phy_up()` do?

**Comment by hasnainvirk** [comment]
k64f_eth_phy_up() functionality can be seen here.
https://github.com/ARMmbed/sal-nanostack-driver-k64f-eth/pull/7

**Comment by hasnainvirk** [comment]
Closing this pull request. A wrapper is created in the Ethernet driver itself for simulating interrupt using a polling method.

**Pull request closed without merging**
